### ISSUE TITLE
Any guidance on using File Upload?

### ISSUE THREAD

**Issue by kkukshtel** [useshortcut/clubhouse-lib#111]
Both the docs and this library lack any information on File uploading. It seems to be the only route that still passes the token through as a query parameter, and the files themselves I'm unclear on if they can be urls or not. Addtionally the docs list the files as being prepended with an "@" sign, but do not explain if this is necessary or not. I was hoping to see a reference implementation here to clear it up, but sadly haven't found one. Any work you can do to make this more clear would be much appreciated!

**Comment by steaks** [comment]
+1 I would have liked some guidance or a code snippet also. Here is the typescript code I ended up using to implement uploading a file.

```
import {File} from "clubhouse-lib";
import * as fs from "fs"; 
import fetch from "node-fetch"; //https://www.npmjs.com/package/node-fetch
import * as FormData from "form-data"; //https://www.npmjs.com/package/form-data

const uploadFile = async (path: string, fileName: string): Promise<File> => {
  const file = fs.createReadStream(path);
  const body = new FormData();
  body.append(fileName, file);
  const apiKey = "{REDACTED}";
  const response = await fetch(`https://api.app.shortcut.com/api/v3/files?token=${apiKey}`, {method: "POST", body});
  const files = await response.json() as File[];
  return files[0];
};
```

**Comment by kkukshtel** [comment]
I was using Pipedream to do this as part of a flow, so here's what did it for me in JS with the REST API. Pipedream auto uploads images to S3, so here I download the file to disk and then POST that to Clubhouse.

[Shout to this workflow as well for handling the download/upload stuff.](//https://pipedream.com/@dylburger/download-file-then-upload-file-via-multipart-form-data-request-p_QPCx7p/edit)


<img width="1003" alt="Screen Shot 2021-09-10 at 1 24 16 PM" src="https://user-images.githubusercontent.com/7715279/132893219-3b1ba16e-741a-4ffe-8960-09186ba9a91e.png">

**Comment by charpeni** [comment]
Closing this in favor of #126.

We are currently rewriting this library to be a generated TypeScript client from a Swagger/OpenAPI schema.

The new version features an example on file upload.
