### ISSUE TITLE
Migrate to Shortcut

### ISSUE THREAD

**Issue by steaks** [useshortcut/clubhouse-lib#112]
On September 14th references to clubhouse.io will be deprecated. And on November 13th references to clubhouse.io will stop working. Instructions for migration: https://shortcut.com/api/rest/v3#Updating-your-application

_I'm guessing this is on your internal roadmap, but just in-case it's not I filed this ticket :)_

**Comment by charpeni** [comment]
Closing this in favor of #126.

We are currently rewriting this library to be a generated TypeScript client from a Swagger/OpenAPI schema.
