### ISSUE TITLE
Unable to update labels for a story

### ISSUE THREAD

**Issue by sksavant** [useshortcut/clubhouse-lib#75]
I am getting a 400 Bad request for `updateStory` in the following:
 
```
labels = await client.listLabels()
client.updateStory(story_id, { labels: [labels[0]] })
``` 
I was able to remove label by sending empty array `labels: []` in params but I am not able to add a label
I tried passing the exact parameters as in API which is `name, description, external_id, color` but it doesn't make any difference

Is there something I am doing wrong?

**Comment by sksavant** [comment]
It works when using only `name` param when adding label

**Comment by charpeni** [comment]
Glad to hear that you got it working!

**Comment by Evilweed** [comment]
@charpeni please reopen this ticket. Tried same solution as mentioned above - does not work.

**Comment by charpeni** [comment]
@Evilweed the exact same issue?

**Comment by charpeni** [comment]
Closing this for now since the original issue is fixed.

**Comment by sksavant** [comment]
For anyone else facing this issue, what worked for me is 
```
const labels = await client.listLabels()
const labelToAdd = labels[0] // label you want to add to story
client.updateStory(story_id, {labels: [ {name: labelToAdd.name} ] })
```
