### ISSUE TITLE
Add support for a getStoryComment call

### ISSUE THREAD

**Issue by mjsz** [useshortcut/clubhouse-lib#79]
I have a simple PR that can be reviewed / merged. Let me know how to get access. Thanks!

**Comment by charpeni** [comment]
I would be happy to review your PR.

What do you mean by how to get access? You should have access to send a pull request along our way.

**Comment by charpeni** [comment]
Closing this in favor of #126.

We are currently rewriting this library to be a generated TypeScript client from a Swagger/OpenAPI schema.
